import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header} from "@/components/shared/header";
import {Footer} from "@/components/shared/footer";
import React from "react";

const myFont = localFont({
  src: [
      {
          path: "./fonts/SFPRODISPLAYREGULAR.woff",
          weight: '400',
          style: 'normal',
      },
      {
          path: "./fonts/SFPRODISPLAYMEDIUM.woff",
          weight: '500',
          style: 'italic',
      },
      {
          path: "./fonts/SFPRODISPLAYBOLD.woff",
          weight: '700',
          style: 'normal',
      },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myFont.className}
      >
      <div className="bg-white">
          <Header/>
          {children}
          <Footer/>
      </div>
      </body>
    </html>
  );
}
